# This is a basic workflow to help you get started with Actions

name: ChulCheck

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # schedule:
    # - cron: "00 15 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Notification Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: '인유 출첵 완료'
          username: '인유 출첵봇'
          channel: '#자동-수행-결과-알림'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
    
      # Runs a single command using the runners shell

