name: ChulCheck

on:
  schedule:
    - cron: "00 10 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install -r requirements.txt
       
      - name: run script
        env:
          ID: ${{ secrets.ID }}
          PW: ${{ secrets.PW }}
        run: python script.py

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Notification Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: '인유 출첵 완료'
          username: '인유 출첵봇'
          channel: '#자동-수행-결과-알림'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
    
      # Runs a single command using the runners shell

