# This is a basic workflow to help you get started with Actions

name: ChulCheck

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 21 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Notification Slack
        uses: actions/checkout@v3
        env:
          SLACK_CHANNEL: 자동-수행-결과-알림
          SLACK_TITLE: 출석 결과
          SLACK_USERNAME: 인유 출석
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK_URL }}
          SLACK_MESSAGE: "출첵 완료"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
